"""email not required

Revision ID: 0e3f8118994f
Revises: 1c04915af6f5
Create Date: 2025-11-12 17:05:46.871219

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core

# revision identifiers, used by Alembic.
revision: str = "0e3f8118994f"
down_revision: Union[str, Sequence[str], None] = "1c04915af6f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "donations", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.create_unique_constraint(None, "email_logs", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "email_logs", type_="unique")
    op.alter_column(
        "donations", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
