"""add email log table

Revision ID: 1c04915af6f5
Revises: b3ce9f0c3597
Create Date: 2025-11-05 19:37:48.737295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core

# revision identifiers, used by Alembic.
revision: str = "1c04915af6f5"
down_revision: Union[str, Sequence[str], None] = "b3ce9f0c3597"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("donation_id", sa.String(length=36), nullable=True),
        sa.Column("recipient_email", sa.String(length=255), nullable=False),
        sa.Column("mail_type", sa.String(length=50), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=False),
        sa.Column("mail_content", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("message_id", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("additional_data", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "deleted_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["donation_id"],
            ["donations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_logs_donation_id"), "email_logs", ["donation_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_logs_is_deleted"), "email_logs", ["is_deleted"], unique=False
    )
    op.create_index(
        op.f("ix_email_logs_mail_type"), "email_logs", ["mail_type"], unique=False
    )
    op.create_index(
        op.f("ix_email_logs_recipient_email"),
        "email_logs",
        ["recipient_email"],
        unique=False,
    )
    op.create_index(
        op.f("ix_email_logs_status"), "email_logs", ["status"], unique=False
    )
    op.create_unique_constraint(None, "admin_access_tokens", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "admin_access_tokens", type_="unique")
    op.drop_index(op.f("ix_email_logs_status"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_recipient_email"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_mail_type"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_is_deleted"), table_name="email_logs")
    op.drop_index(op.f("ix_email_logs_donation_id"), table_name="email_logs")
    op.drop_table("email_logs")
    # ### end Alembic commands ###
