"""update models

Revision ID: a23156d23577
Revises: e648ee7af357
Create Date: 2025-08-23 00:57:24.126373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core

# revision identifiers, used by Alembic.
revision: str = 'a23156d23577'
down_revision: Union[str, Sequence[str], None] = 'e648ee7af357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'donations', ['order_id'])
    op.create_unique_constraint(None, 'donations', ['id'])
    op.create_unique_constraint(None, 'form_g80_submissions', ['id'])
    op.create_unique_constraint(None, 'phonepe_payment_logs', ['merchant_order_id'])
    op.create_unique_constraint(None, 'phonepe_payment_logs', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phonepe_payment_logs', type_='unique')
    op.drop_constraint(None, 'phonepe_payment_logs', type_='unique')
    op.drop_constraint(None, 'form_g80_submissions', type_='unique')
    op.drop_constraint(None, 'donations', type_='unique')
    op.drop_constraint(None, 'donations', type_='unique')
    # ### end Alembic commands ###
