"""add indexes

Revision ID: a9913b104c13
Revises: a23156d23577
Create Date: 2025-08-23 00:59:21.202184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core

# revision identifiers, used by Alembic.
revision: str = "a9913b104c13"
down_revision: Union[str, Sequence[str], None] = "a23156d23577"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("donations_order_id_key"), "donations", type_="unique")
    op.create_index(
        op.f("ix_donations_need_g80_certificate"),
        "donations",
        ["need_g80_certificate"],
        unique=False,
    )
    op.create_index(
        op.f("ix_donations_order_id"), "donations", ["order_id"], unique=True
    )
    op.create_index(op.f("ix_donations_status"), "donations", ["status"], unique=False)
    op.create_index(
        op.f("ix_form_g80_submissions_donation_id"),
        "form_g80_submissions",
        ["donation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_form_g80_submissions_status"),
        "form_g80_submissions",
        ["status"],
        unique=False,
    )
    op.drop_constraint(
        op.f("phonepe_payment_logs_merchant_order_id_key"),
        "phonepe_payment_logs",
        type_="unique",
    )
    op.create_index(
        op.f("ix_phonepe_payment_logs_merchant_order_id"),
        "phonepe_payment_logs",
        ["merchant_order_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_phonepe_payment_logs_payment_status"),
        "phonepe_payment_logs",
        ["payment_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_phonepe_payment_logs_phonepe_order_id"),
        "phonepe_payment_logs",
        ["phonepe_order_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_phonepe_payment_logs_phonepe_order_id"),
        table_name="phonepe_payment_logs",
    )
    op.drop_index(
        op.f("ix_phonepe_payment_logs_payment_status"),
        table_name="phonepe_payment_logs",
    )
    op.drop_index(
        op.f("ix_phonepe_payment_logs_merchant_order_id"),
        table_name="phonepe_payment_logs",
    )
    op.create_unique_constraint(
        op.f("phonepe_payment_logs_merchant_order_id_key"),
        "phonepe_payment_logs",
        ["merchant_order_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(
        op.f("ix_form_g80_submissions_status"), table_name="form_g80_submissions"
    )
    op.drop_index(
        op.f("ix_form_g80_submissions_donation_id"), table_name="form_g80_submissions"
    )
    op.drop_index(op.f("ix_donations_status"), table_name="donations")
    op.drop_index(op.f("ix_donations_order_id"), table_name="donations")
    op.drop_index(op.f("ix_donations_need_g80_certificate"), table_name="donations")
    op.create_unique_constraint(
        op.f("donations_order_id_key"),
        "donations",
        ["order_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
