"""add admin access token table

Revision ID: b3ce9f0c3597
Revises: bf7c5d3ce2b0
Create Date: 2025-09-16 19:53:46.104115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core

# revision identifiers, used by Alembic.
revision: str = "b3ce9f0c3597"
down_revision: Union[str, Sequence[str], None] = "bf7c5d3ce2b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_access_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column(
            "expiry",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_admin_access_tokens_token"),
        "admin_access_tokens",
        ["token"],
        unique=True,
    )
    op.create_unique_constraint(None, "sbiepay_payment_logs", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sbiepay_payment_logs", type_="unique")
    op.drop_index(
        op.f("ix_admin_access_tokens_token"), table_name="admin_access_tokens"
    )
    op.drop_table("admin_access_tokens")
    # ### end Alembic commands ###
