"""update max length

Revision ID: b993ba80ca0c
Revises: a9913b104c13
Create Date: 2025-09-01 16:58:11.554232

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core

# revision identifiers, used by Alembic.
revision: str = "b993ba80ca0c"
down_revision: Union[str, Sequence[str], None] = "a9913b104c13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phonepe_payment_logs",
        "redirect_url",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "phonepe_payment_logs",
        "redirect_url",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=512),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
