"""add sbi payment gateway

Revision ID: bf7c5d3ce2b0
Revises: b993ba80ca0c
Create Date: 2025-09-12 19:45:18.943816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import core

# revision identifiers, used by Alembic.
revision: str = "bf7c5d3ce2b0"
down_revision: Union[str, Sequence[str], None] = "b993ba80ca0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sbiepay_payment_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("merchant_order_id", sa.String(length=128), nullable=False),
        sa.Column("sbiepay_ref_id", sa.String(length=128), nullable=True),
        sa.Column("encrypted_trans", sa.Text(), nullable=False),
        sa.Column("payment_status", sa.String(length=32), nullable=False),
        sa.Column("customer_id", sa.String(length=100), nullable=True),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("sbiepay_response_data", sa.JSON(), nullable=True),
        sa.Column("double_verification_data", sa.JSON(), nullable=True),
        sa.Column("pay_mode", sa.String(length=50), nullable=True),
        sa.Column("bank_code", sa.String(length=20), nullable=True),
        sa.Column("bank_reference_number", sa.String(length=100), nullable=True),
        sa.Column("transaction_date", sa.String(length=20), nullable=True),
        sa.Column("reason_message", sa.String(length=500), nullable=True),
        sa.Column("other_details", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "deleted_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_sbiepay_payment_logs_is_deleted"),
        "sbiepay_payment_logs",
        ["is_deleted"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sbiepay_payment_logs_merchant_order_id"),
        "sbiepay_payment_logs",
        ["merchant_order_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_sbiepay_payment_logs_payment_status"),
        "sbiepay_payment_logs",
        ["payment_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sbiepay_payment_logs_sbiepay_ref_id"),
        "sbiepay_payment_logs",
        ["sbiepay_ref_id"],
        unique=False,
    )
    op.add_column(
        "donations",
        sa.Column(
            "payment_provider",
            sa.String(length=50),
            server_default="phonepe",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("donations", "payment_provider")
    op.drop_index(
        op.f("ix_sbiepay_payment_logs_sbiepay_ref_id"),
        table_name="sbiepay_payment_logs",
    )
    op.drop_index(
        op.f("ix_sbiepay_payment_logs_payment_status"),
        table_name="sbiepay_payment_logs",
    )
    op.drop_index(
        op.f("ix_sbiepay_payment_logs_merchant_order_id"),
        table_name="sbiepay_payment_logs",
    )
    op.drop_index(
        op.f("ix_sbiepay_payment_logs_is_deleted"), table_name="sbiepay_payment_logs"
    )
    op.drop_table("sbiepay_payment_logs")
    # ### end Alembic commands ###
