"""add db structure


Revision ID: e648ee7af357
Revises:
Create Date: 2025-08-22 18:13:38.559352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core

# revision identifiers, used by Alembic.
revision: str = "e648ee7af357"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "donations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=50), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("contact_number", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("need_g80_certificate", sa.Boolean(), nullable=False),
        sa.Column("confirmed_terms", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "deleted_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_donations_is_deleted"), "donations", ["is_deleted"], unique=False
    )
    op.create_table(
        "phonepe_payment_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("merchant_order_id", sa.String(length=128), nullable=False),
        sa.Column("phonepe_order_id", sa.String(length=128), nullable=False),
        sa.Column("redirect_url", sa.String(length=512), nullable=True),
        sa.Column("payment_status", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("phonepe_payment_details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "deleted_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_phonepe_payment_logs_is_deleted"),
        "phonepe_payment_logs",
        ["is_deleted"],
        unique=False,
    )
    op.create_table(
        "form_g80_submissions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("donation_id", sa.String(length=36), nullable=False),
        sa.Column("pan_number", sa.String(length=20), nullable=False),
        sa.Column("full_address", sa.String(length=1000), nullable=False),
        sa.Column("city", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=128), nullable=False),
        sa.Column("country", sa.String(length=128), nullable=False),
        sa.Column("pin_code", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "deleted_at",
            core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["donation_id"],
            ["donations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_form_g80_submissions_is_deleted"),
        "form_g80_submissions",
        ["is_deleted"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_form_g80_submissions_is_deleted"), table_name="form_g80_submissions"
    )
    op.drop_table("form_g80_submissions")
    op.drop_index(
        op.f("ix_phonepe_payment_logs_is_deleted"), table_name="phonepe_payment_logs"
    )
    op.drop_table("phonepe_payment_logs")
    op.drop_index(op.f("ix_donations_is_deleted"), table_name="donations")
    op.drop_table("donations")
    # ### end Alembic commands ###
